### ISSUE TITLE
moderation extension appears to auto-log out just created users

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#11]
I think I've just tracked down an issue with out mediawiki installation auto-logging out newly created users to the moderation extension.

Here are some details:

When I create an account on our [bitnami mediawiki installation](http://bitnami-mediawiki-c678.cloudapp.net/) it creates the following cookies:

![cookies created for new user account](https://www.dropbox.com/s/f73wmvq1g31uh6o/Screenshot%202017-05-15%2010.56.38.png?dl=1)

When I navigate to the main page I get logged out, and just one cookie remains:

![single cookie after redirect](https://www.dropbox.com/s/mha525jx20y2yow/Screenshot%202017-05-15%2011.00.21.png?dl=1)

Navigating around I stay logged out, and then I can log in which generates a couple more cookies:

![more cookies after login](https://www.dropbox.com/s/h68yx9n2tz9jpv5/Screenshot%202017-05-15%2011.01.59.png?dl=1)

I reported this issue on the mediawiki support desk for another bitnami mediawiki installation: 

https://www.mediawiki.org/wiki/Topic:Tqcpaksxynh43c8w

and they confirmed the problem with the cookies ...

So the fact that this was happening on our staging box made it seem like this was a bitnami mediawiki issue, or possibly something to do with the extensions we had configured on both.  So far the only extensions configured on the staging site are the moderation extension and the wikieditor.  Those two extensions are also on the main site.

When I tried disabling the wikieditor AND the moderation extension, and then create account maintained a login.  I re-enabled the wikieditor and create account again maintained the cookies for login after account creation:

![moderation disabled and cookies maintained](https://www.dropbox.com/s/1jvwaysnndj81bq/Screenshot%202017-05-15%2011.20.59.png?dl=1)

 appearing to confirm that the moderation extension was the culprit.  For an extra check re-enabled moderation and disabled the wikieditor, and the problem returned:

![cookies after create account with moderation enabled missing the UserName cookie](https://www.dropbox.com/s/squ3liuayrvzqq4/Screenshot%202017-05-15%2011.22.19.png?dl=1)

This is a pretty serious issue for non-technical users of our instances using the moderation extension, as the user creates their account, and on that page they are told they are logged in.   They navigate away lose their login and don't know realise, and think they don't have permission to edit anything ...

**Comment by edwardspec** [comment]
There is only one place where Moderation could theoretically affect login.

Please do the following test:
1) in hooks/ModerationPreload.php, add "return true;" immediately after the line
`public static function onLocalUserCreated( $user, $autocreated ) {`
2) Let me know if the issue disappeared.

**Comment by tansaku** [comment]
@edwardspec yes - that made the issue go away

**Comment by edwardspec** [comment]
Good, now I know the solution
(to untie ModerationPreload class from the global RequestContext, so that it wouldn't change $wgUser).

**Comment by edwardspec** [comment]
Should be fixed in 1.0.21.
Please confirm it works.

**Comment by tansaku** [comment]
this appears fixed on both my production and staging environments - many thanks!
