### ISSUE TITLE
Could the moderation message be configured to include eye-catching icon?

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#12]
I've been conducting usability tests with many users and it seems that the majority of people just don't read what's in the moderation message and then get confused when their edit does not appear.

I'm wondering if a more eye-catching icon in the pop-up might be helpful - even something that appeared in the page like the the things that get added to wikipedia articles to indicate changes are required:

![](https://www.dropbox.com/s/1mtmqoxa30ewpcj/Screenshot%202017-05-17%2009.36.04.png?dl=1)

I think it's an uphill battle because the majority of people just don't read stuff, but maybe an eye-catching icon to indicate that moderation approval is pending could be the thing to give them a chance to realise their change is saved, but awaiting approval ...

**Comment by edwardspec** [comment]
Can be easily added.
Any suggestions on what image to use?

**Comment by tansaku** [comment]
something like this might be good ():

https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Icon_stamp_under_Review_textured_askew.svg/1000px-Icon_stamp_under_Review_textured_askew.svg.png

but I think it's important that it's red - my first searches came up with:

![red under review icons](https://www.dropbox.com/s/niqgilzrupduq2z/Screenshot%202017-05-18%2010.43.21.png?dl=1)

I think people take slightly more notice of a message popup when it has red ... at least they don't assume that nothing has happened ...

**Comment by edwardspec** [comment]
Text within the image is not translatable (important for non-English wikis).
We can place the text above the image though (CSS position).

I'll look for some icons without the text.

**Comment by tansaku** [comment]
hmm I wonder if there's an under review red font we could use?

**Comment by tansaku** [comment]
or make the image a config setting so that users can configure which image they use ...

**Comment by edwardspec** [comment]
> or make the image a config setting so that users can configure which image they use ...

No, that would force every non-English wiki to find an image for themselves - very inconvenient.
Any displayed text should be easily translatable (via i18/*.json), not hardcoded into the image.

**Comment by edwardspec** [comment]
I'll experiment with styles for a while and let you know.

**Comment by edwardspec** [comment]
Would this be ok?
![pending-review-20170521](https://cloud.githubusercontent.com/assets/1163218/26285124/1c1e3512-3e52-11e7-903e-d45226f1a40e.png)

**Comment by tansaku** [comment]
@edwardspec that's a step in the right direction - would love a config to allow us to insert what we wanted :-)

**Comment by edwardspec** [comment]
Add the following to MediaWiki:Common.css:

```
#pending-review {
	background-image: url('http://example.com/image.png'); /* URL of your image */
	font-size: 1px;
	border: 0;
	width: 300px;
	height: 200px;
}
```

**Comment by edwardspec** [comment]
If the screenshot above is so absolutely terrible, please let me know so that I could revert this change.
We might as well have `#pending-review` as an empty `<div>`.

**Comment by tansaku** [comment]
it's a great first pass - at the very least the red box will catch people's attention - definitely an improvement - but the layout could be improved - but rather than having you tweak it I would set that red box thing as the default, but also allow it to be overidden with something else

**Comment by edwardspec** [comment]
> but also allow it to be overidden with something else

Does the MediaWiki:Common.css tweak (see above) work for you?
It does exactly that (locally for your wiki).

**Comment by edwardspec** [comment]
Closing as resolved.

1) MediaWiki:Common.css solution (see above) allows to customize the icon on per-wiki basis.
2) If there will be specific suggestions on how to improve the default message (without injecting the non-translatable text as an image), we'll improve it then.
