### ISSUE TITLE
dealing with spammers

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#14]
Not sure if this is the right place, but now our wiki is live we are getting a fair amount of spam

Moderation is working perfectly, but the user list and moderation list is getting a bit full of junk - would it be possible to have a moderation view that filtered out all spammers, and a user list that filtered out all those who had been marked as spammers?

**Comment by edwardspec** [comment]
Moderation is not against automatic spambots.
It helps, but you shouldn't sit and manually moderate 1000 spam edits when you make write 2-3 filters in Extension:AbuseFilter, thus preventing them from appearing in the first place.

Spambots target thousands of wikis at the same time (not your wiki specifically), so they can't adapt to your countermeasures, therefore AbuseFilter, SpamBlacklist, ConfirmEdit, etc. are super effective.

The action "Mark as spammer" is not against bots. It's against human spammers/vandals - if you are tired of rejecting the edits from some user. Their further edits will end up in "Spam" folder of Special:Moderation.

Spambots will usually create a new account every time they go spamming, so it's not helpful against them at all.

**Comment by tansaku** [comment]
so sounds like installing one of AbuseFilter, SpamBlacklist, ConfirmEdit is the way to go then? thanks :-)
