### ISSUE TITLE
could clicking on links like "Mark as Spammer" popup result and stay on main listing rather than redirecting?

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#15]
A "power user" request perhaps, but at the moment if I want to go through marking people as spammers I keep getting directed to a page that says something like:

"so and so marked as spammer"

when what I'd prefer is to stay on the list and have my action confirmed with a popup rather than a new page - make sense?

**Comment by tansaku** [comment]
at the moment I manage the issue by holding down command when clicking on these things which opens the new page in a tab so I can stay on the listing page and mark several folks as spammers in a row ...

**Comment by tansaku** [comment]
example of the simple info pages that might be better as popups:

![](https://www.dropbox.com/s/pk2dwb6la6ebdst/Screenshot%202017-06-08%2009.44.11.png?dl=1)

**Comment by edwardspec** [comment]
Indeed, these links should work via Ajax.

Such feature must be thoroughly covered by Selenium tests though.
Currently Approve/Reject/... links are tested by phpunit testsuite (which won't help with Ajax).

Need to resolve SauceLabs-related issues (mentioned in #13) first.

**Comment by edwardspec** [comment]
This is a low-priority task.

It requires much to do and is a very minor improvement.
It's very convenient to open these actions in tabs (click them with middle mouse button).

Firefox, Chrome and Edge have "Close other tabs" and "Close tabs to the right" menu options when you right-click on the tab. Safari has "Close other tabs".

**Comment by edwardspec** [comment]
I've implemented Ajax handling of the following links:
"Approve", "Approve all", "Reject", "Reject all", "Mark as spammer", "No longer a spammer".

Comment of 1cfb5931230162dc3e0133bac69c895421b50614 explains why show/merge actions were skipped for now.

@tansaku Could you please have a look at the current state of the feature?
(`$wgModerationUseAjax = true;` in LocalSettings.php to enable)

From UX perspective - is it convenient or not? Anything I should improve?
What do you think we should do when moderator clicks "diff" link (modaction=show)?

**Comment by tansaku** [comment]
thanks @edwardspec - I'm travelling at the moment - will try to look soon

**Comment by edwardspec** [comment]
Closing due to no feedback.
This feature may be revisited next time someone requests it.
