### ISSUE TITLE
once a user is marked as auto-moderated, do their merges no longer show up?

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#17]
I'm certain I'm merged changes from many users.  Those trusted users have all quickly been marked for auto-moderation.  Does auto-moderation somehow mean that users merged submissions no longer show up in the merged results?

![](https://www.dropbox.com/s/x9qlop23s08fwud/Screenshot%202017-06-08%2009.50.40.png?dl=1)

**Comment by edwardspec** [comment]
1. "Merged" folder shows changes where the moderator has manually resolved an edit conflict.
2. Edits which were Approved (but didn't have an edit conflict) are not shown on Special:Moderation.
3. Making the user "automoderated" only affects his/her future edits. If some edits were queued for moderation before that, they won't be auto-approved or something.
