### ISSUE TITLE
confirmEdit in combination with Moderation

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#18]
I was just trying confirmEdit in combination with Moderation and I notice I get an error if I try to submit a URL from a moderated user:

![error if I try to submit a URL from a moderated user](https://www.dropbox.com/s/j81hp6ebhgguco6/Screenshot%202017-06-16%2016.23.12.png?dl=1)

**Comment by tansaku** [comment]
I was just submitting a link to google ...

**Comment by edwardspec** [comment]
In MediaWiki 1.28 + Extension:ConfirmEdit (ReCaptchaNoCaptcha), I see this error even without Moderation.
