### ISSUE TITLE
Rejected Pages should be appear and editable back to user(owner of Page) 

### ISSUE THREAD

**Issue by pramod-linux** [edwardspec/mediawiki-moderation#20]
I used this extention in mediawiki-1.28. It's working perfect but in case of page reject, user can't view it again.

**Comment by edwardspec** [comment]
It's intentional.
Per https://www.mediawiki.org/wiki/Extension:Moderation#Recommended_use_.2F_good_practices ,
> Only vandalism should be Rejected. Not-so-good edits with good intentions (e.g. adding excessive plot details into the Wikipedia article about film) are better made Approved and then reverted as usual. This way the author is not offended and the text is saved in page history, viewable by anyone.

You shouldn't be rejecting an edit if its contents aren't useless later on.

**Comment by pramod-linux** [comment]
Thanks for your support,
Actually we are configuring mediawiki with moderation extention and we want that rejected pages should be visible to owner of page so that user can change on page again.
**For Example-** User **A** created a new page on wiki and saved it, now page will be send for moderation and moderator rejected this page, now it should be visible to user again.
But in my case it's not visible to user, if I search this page on wiki then i got message "_There were no results matching the query._" .

**Comment by edwardspec** [comment]
Moderation is an anti-vandalism extension, not a quality review extension.
This feature won't be needed for 99.9% of wikis.

You can achieve desired behavior by editing `action/ModeratioActionReject.php` and replacing
`'mod_preloadable' => 0`
with 
`'mod_preloadable' => 1`
This will make the pending changes editable by their author even if rejected.

**Comment by pramod-linux** [comment]
Thankyou so much.
I made these changes and working fine.

Q. Is there any option to check rejected pages for a particular author(user) after login.

**Comment by edwardspec** [comment]
No, there is no such feature.
As a moderator, you can just open Rejected folder with &limit=5000 and use your browser's Find.

I thought about making "status of my pending changes" page (where the user could see **his/her own** non-approved changes), but decided against it for motivational reasons.
Important benefit of Moderation is that it demotivates vandalism out of being noticed. Like writing "admin is idiot" in articles. Such page will be seen as "My evil accomplishments"; without it, vandal's activity just becomes nothing.

**Comment by pramod-linux** [comment]
Thanks a lot for your valuable time.
