### ISSUE TITLE
any concerns about deleting users that are being moderated?

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#21]
hi @edwardspec - thanks for your previous suggestions for ConfirmEdit - ReCaptcha on our sign up page has taken spambots to zero.

We're now thinking about deleting all the users that the spambots created.  Seems like https://www.mediawiki.org/wiki/Manual:RemoveUnusedAccounts.php might be simplest.  Do you think there would be any strange side-effects on the moderation system with these spam users being deleted?

I did a trial run on our staging server and seems fine, but I didn't go so far as trying to approve a deleted users contribution, although that's a pretty rare corner case as I wouldn't run this script with pending items for moderation ...

**Comment by edwardspec** [comment]
Uploads will be non-approvable (pending upload is stored in the user's image stash, and removing the account deletes the stash). Will show "moderation-missing-stashed-image" error.

Approved edits will be anonymous (rev_user=0), just like the edits from IP.

**Comment by edwardspec** [comment]
One thing I need to fix here is `rev_user_text` after approval.
It `mod_user` was deleted, it seems that rev_user_text would contain IP of moderator (should be `mod_user_text`).

**Comment by edwardspec** [comment]
Fixed rev_user_text when approving edits made by deleted users.
Also added a test for this situation.
