### ISSUE TITLE
possible to include dates on moderation pages?

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#22]
I just noticed that we seem to have time but not dates on the moderation pages:

<img width="1266" alt="screenshot 2017-08-07 11 39 49" src="https://user-images.githubusercontent.com/30216/29201657-1d10b9a2-7e9b-11e7-8152-e2046597183c.png">

It would be useful to have a short format date in there if that was possible - thanks :-)

**Comment by edwardspec** [comment]
Date is already shown as a tooltip when you hover the mouse above the time.
Does this work for you?

**Comment by tansaku** [comment]
Ah I see that now - good to know it's there - not so easily discoverable - on our wiki the date would probably more useful than time.  Or maybe both if the title was shortened to some max number of chars?

**Comment by edwardspec** [comment]
Added the date.
