### ISSUE TITLE
feature request - emailing users about accepted submissions

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#24]
Not sure if this is crazy, or even already available, but I'd love to have it set up to automatically email users when they've had their submissions approved, and be able to cc that email to a few different emails ... completely out of scope here?

**Comment by edwardspec** [comment]
I don't think this is necessary.
To quote from https://www.mediawiki.org/w/index.php?title=Extension_talk:Moderation&oldid=2534539#Works_with_Echo.3F

> Generally, a user would want to be notified "my edit was approved/rejected" only if he/she doesn't know whether it will be approved or rejected. For example, on a humor site where "funny jokes are approved, non-funny are rejected". When following Good Practices 1 _[Only vandalism should be Rejected. Not-so-good edits with good intentions (e.g. adding excessive plot details into the Wikipedia article about film) are better made Approved and then reverted as usual]_, **approval is assured if the edit wasn't made with bad intent**.

If someone else contributes such code, I'll merge it, but I don't plan to implement it myself.

**Comment by edwardspec** [comment]
> and be able to cc that email to a few different emails 

Definitely no.

Basically, you want to get an email for each entry in Special:Log that interests you.
This is not Moderation-specific (another wiki might want to be notified about new uploads, and another about renamed pages) and should be in a separate extension.
