### ISSUE TITLE
Use of AuthPluginAutoCreate hook was deprecated

### ISSUE THREAD

**Issue by mudrd8mz** [edwardspec/mediawiki-moderation#25]
Hi. Thanks for this extension. It works very well for us and does exactly what we've been looking for.

When testing on our 1.27 installation, our testers ran into the following PHP notices:
```
Deprecated: Use of AuthPluginAutoCreate hook
(used in ModerationEditHooks::onAuthPluginAutoCreate)
was deprecated in MediaWiki 1.27.
[Called from MediaWiki\Auth\AuthManager::autoCreateUser in                      
.../includes/auth/AuthManager.php at line 1652]
in .../includes/debug/MWDebug.php on line _300_  
```
Any plans on updating the extension to use an alternative hook? Thanks in advance.

**Comment by mudrd8mz** [comment]
https://www.mediawiki.org/wiki/Manual:Hooks/AuthPluginAutoCreate

**Comment by edwardspec** [comment]
Fixed in 1.0.45.

In MediaWiki 1.27+, this hook is not needed (LocalUserCreated hook does the same thing), so I removed it from extension.json.
Older MediaWiki (we still support 1.23) use Moderation.php, not extension.json.

**Comment by mudrd8mz** [comment]
Thanks for the prompt reply.

> Fixed in 1.0.45.

Sorry, I haven't seen that among tags / releases here on github. Is there a better place for checking the latest versions (production ready) of this extension?

**Comment by edwardspec** [comment]
The master branch is production ready.
A full testsuite run (for 1.29, 1.27 and 1.23) is performed before every push/merge there.

Things that are not production ready are developed in other branches.

The version I mentioned is for internal use. It's stored in extension.json and updated on every commit.

**Comment by mudrd8mz** [comment]
Great! Thanks for the explanation, that's good to know.
