### ISSUE TITLE
[Request] Send notifications e-mails

### ISSUE THREAD

**Issue by thiagofasano** [edwardspec/mediawiki-moderation#28]
Is there a possibility of being sent by notification email when a page is submitted for moderation?

I tried to activate, But he did not return any notification emails:

$wgModerationNotificationEnable = true;
$wgModerationNotificationNewOnly = false;
$wgModerationEmail = $wgEmergencyContact;

**Comment by edwardspec** [comment]
Is your `$wgEmergencyContact` variable set to the email address where you want to receive notifications?

If not, set $wgModerationEmail to the correct address, e.g.
`$wgModerationEmail = "my-email@example.com";`

**Comment by thiagofasano** [comment]
Perfect, thanks.
