### ISSUE TITLE
interaction with Semantic MediaWiki

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#29]
Happy New Year! :-)

Just a quick note that we added https://www.mediawiki.org/wiki/Extension:Semantic_MediaWiki to our wiki with moderation and running some of the automated updates, we notice they get caught in the moderation system:

![](https://dl.dropbox.com/s/3txqanykwftla0q/Screenshot%202018-01-02%2011.50.11.png?dl=0)

where we notice they can't be approved since they involve no changes to the text:

![](https://dl.dropbox.com/s/qrp1x3nbx6ua84g/Screenshot%202018-01-02%2011.50.55.png?dl=0)

I'm not sure if this is actually a problem per se.  Maybe the SM extension touched, but didn't change some pages?  Anyway, to clear up our moderation page it would be good if we could "approve" these "changes" ... although perhaps "rejecting" them will have no negative impact on the SM functionality ...?

**Comment by edwardspec** [comment]
These changes can be safely rejected.

This error message ("[...] no change was made to the text") means that this page (e.g. Property:Foat:knows) already has exactly the same text as this change wants to add. So approving is not needed.

I guess the update script tried to import the pages that already existed in your wiki, and this caused "zero edits" to appear in the moderation queue.

**Comment by edwardspec** [comment]
Moderation doesn't silently delete "zero edits", because sometimes users write meaningful things in the edit summary when doing them.
