### ISSUE TITLE
is there a way to get a non-diff view of a submitted item?

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#30]
We've just had a submission that I'd like to share with others via email but the diff view makes it difficult for me to take a simple copy of the change (in this case a couple of paragraphs on a new page).

Is there a simple way to see the submitted content in something other than diff format?

**Comment by edwardspec** [comment]
Does `?modaction=preview` (instead of `?modaction=show`) work for you?

**Comment by edwardspec** [comment]
Also please provide feedback on #15 (the feature you previously requested).
Need to know whether it's convenient to use or not.

**Comment by tansaku** [comment]
`?modaction=preview` works just as we need thanks :-)
