### ISSUE TITLE
Unable to find the Moderation page in Special Pages

### ISSUE THREAD

**Issue by sudhirnagendragupta** [edwardspec/mediawiki-moderation#31]
Hi,
I did the installation for moderation extension by following the steps mentioned on the extension mediawiki page.
But unable to find the moderation page on special pages.
The php settings may be wrong. Can i get some help here?

**Comment by edwardspec** [comment]
It's shown for me.
When you visited Special:SpecialPages, where you logged in as a user who has 'moderation' right? (it shows only pages that the current user is allowed to access)

**Comment by sudhirnagendragupta** [comment]
Hey thanks Edward,

I thought, the admin would be the moderator by default.

I changed the user rights and it works well now.

Thanks a lot !



Regards
Sudhir Gupta
