### ISSUE TITLE
Exclude Namespaces

### ISSUE THREAD

**Issue by kaddigat** [edwardspec/mediawiki-moderation#33]
Is it possible to exclude several namespaces from the extension?

**Comment by edwardspec** [comment]
Not at the moment.

Originally Moderation was designed as anti-vandal extension, and if you allow unrestricted editing of some pages, vandals will target them (e.g. if only articles are moderated, vandals can go to User_talk to insult users instead of vandalizing articles).

That being said,
are the situations when this feature would be useful?

**Comment by kaddigat** [comment]
You are of course right with protection against vandals. 

However, I would like to use File uploads without the moderation extension. The reason is that I use custom Forms (Page Forms Extension) for the File upload to be able to add more information to the Files (properties,categories,...). To do that I use the workaround described here: https://www.mediawiki.org/wiki/Extension:Page_Forms/Manual/Using_Semantic_Forms_for_file_pages_and_uploads#The_one-step_process Unfortunately this workaround is not compatible with the Moderation Extension right now. The reason is that the first step is to upload the File - which needs permission. I know that the method is a workaround, but I did not find any other "simple" method to create a custom upload form that is compatible with your extension. So the easiest way (by far not perfect) would be to exclude the File namespace.

**Comment by kaddigat** [comment]
With protecting talk pages you are of course right - however for many wikis it may decrease the workload a lot to start with protecting only the main namespace. 
For the case that vandalism occurs, one could then simply expand the protection to all namespaces

**Comment by edwardspec** [comment]
Implemented in 1.1.20.

To disable moderation in File and User namespaces:
`$wgModerationIgnoredInNamespaces = [ NS_FILE, NS_USER ];`

To have moderation only in main and Project namespaces:
`$wgModerationOnlyInNamespaces = [ NS_MAIN, NS_PROJECT ];`

**Comment by kaddigat** [comment]
Works fine for me, thank you.
