### ISSUE TITLE
Gerrit hosting?

### ISSUE THREAD

**Issue by sau226** [edwardspec/mediawiki-moderation#36]
[This link](https://mediawiki.org/wiki/Special:MyLanguage/Gerrit/New_repositories) says that we can have the code put up on the Wikimedia server with a 1 click downloader for the extension page. Is it fine if I ask for it to be set up or do you have a problem with it @edwardspec?

**Comment by sau226** [comment]
I also forgot that they also have github mirrors for it jst so you can be sure.

**Comment by edwardspec** [comment]
I don't plan to move Moderation to Gerrit.

Review system of Gerrit is ridiculous and takes a lot of extra time.
There are also idiotic rules on "+2" usage like "if the project has more than 1 active contributor, then you can't apply your own edits without some other person reviewing them, and if you do this regularly, your right to +2 may be revoked". This is totally reasonable for software that launches spaceships (something I developed in the past), but most unreasonable for a CMS extension.

In their current state, automated tests of Moderation expect availability of HTTP server by network, which means they can't be automatically tested by Jenkins as they have it configured on Gerrit.

Our master branch also supports all non-obsolete versions of MediaWiki (unlike the Wikimedia approach  with branches REL1_27, REL1_30, etc., where only the last branch is updated, and old versions of MediaWiki receive no extension updates). If such project is placed on Gerrit, some people with global "+2" may be breaking things by doing commits that only work in the latest version of MediaWiki (on GitHub I can notice this when testing a pull request).

And last but not least, the repository on GitHub is an important part of one's portfolio, while repository in Gerrit is absolutely nothing in the eyes of potential recruiters.

If you want a direct download link, GitHub also has it: https://github.com/edwardspec/mediawiki-moderation/archive/master.zip

**Comment by sau226** [comment]
Err is it fine if I mirror it on a non Wikimedia gerrit I found where project owners get full admin with the server admins only doing what is necessary? Also that one also has a github import tool built in (for pull requests) and I also believe that you can set up CI to work with it.

The site is [gerrithub](http://gerrithub.io/)

**Comment by edwardspec** [comment]
Once again: this is not needed.

**Comment by edwardspec** [comment]
Once again: this is NOT needed.

**Comment by sau226** [comment]
At the very least could you find a collaborator that isn't me that has contributed a lot to this repo (apart from you) and make it so that on a new "stable" branch all Pull Requests have to be reviewed by both of you?

**Comment by edwardspec** [comment]
If your company policy requires proofreading of all used software by at least 2 developers, you should hire a paid developer to do it.
