### ISSUE TITLE
Error: 1146 Table 'bitnami_mediawiki.moderation' doesn't exist 

### ISSUE THREAD

**Issue by savaged** [edwardspec/mediawiki-moderation#40]
Trying to install using the [https://www.mediawiki.org/wiki/Extension:Moderation](guide) and I get Error: 1146 when browsing to update.php or any of our wiki pages. We are using the bitnami_mediawiki stack on Google Cloud. The Moderation extension is the last one in my LocalSettings.php

Here's the detail:
MediaWiki internal error.

Original exception: [610eba0ec92ce462efd71533] /Update.php Wikimedia\Rdbms\DBQueryError from line 1149 of /opt/bitnami/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: SELECT mod_timestamp FROM `moderation` FORCE INDEX (moderation_folder_pending) WHERE mod_rejected = '0' AND mod_merged_revid = '0' LIMIT 1 
Function: ModerationNotifyModerator::getPendingTimeUncached
Error: 1146 Table 'bitnami_mediawiki.moderation' doesn't exist (localhost:3306)

Backtrace:
#0 /opt/bitnami/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php(979): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#1 /opt/bitnami/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php(1343): Wikimedia\Rdbms\Database->query(string, string)
#2 /opt/bitnami/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php(1169): Wikimedia\Rdbms\Database->select(string, string, array, string, array, array)
#3 /opt/bitnami/apps/mediawiki/htdocs/extensions/Moderation/hooks/ModerationNotifyModerator.php(106): Wikimedia\Rdbms\Database->selectField(string, string, array, string, array)
#4 /opt/bitnami/apps/mediawiki/htdocs/extensions/Moderation/hooks/ModerationNotifyModerator.php(84): ModerationNotifyModerator::getPendingTimeUncached()
#5 /opt/bitnami/apps/mediawiki/htdocs/extensions/Moderation/hooks/ModerationNotifyModerator.php(48): ModerationNotifyModerator::getPendingTime()
#6 /opt/bitnami/apps/mediawiki/htdocs/includes/Hooks.php(177): ModerationNotifyModerator::onGetNewMessagesAlert(string, array, User, OutputPage)
#7 /opt/bitnami/apps/mediawiki/htdocs/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#8 /opt/bitnami/apps/mediawiki/htdocs/includes/skins/Skin.php(1401): Hooks::run(string, array)
#9 /opt/bitnami/apps/mediawiki/htdocs/includes/skins/SkinTemplate.php(399): Skin->getNewtalks()
#10 /opt/bitnami/apps/mediawiki/htdocs/includes/skins/SkinTemplate.php(249): SkinTemplate->prepareQuickTemplate()
#11 /opt/bitnami/apps/mediawiki/htdocs/includes/OutputPage.php(2442): SkinTemplate->outputPage()
#12 /opt/bitnami/apps/mediawiki/htdocs/includes/MediaWiki.php(858): OutputPage->output(boolean)
#13 /opt/bitnami/apps/mediawiki/htdocs/includes/MediaWiki.php(870): MediaWiki->{closure}()
#14 /opt/bitnami/apps/mediawiki/htdocs/includes/MediaWiki.php(523): MediaWiki->main()
#15 /opt/bitnami/apps/mediawiki/htdocs/index.php(43): MediaWiki->run()
#16 {main}

Exception caught inside exception handler: [610eba0ec92ce462efd71533] /Update.php Wikimedia\Rdbms\DBQueryError from line 1149 of /opt/bitnami/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: SELECT mod_timestamp FROM `moderation` FORCE INDEX (moderation_folder_pending) WHERE mod_rejected = '0' AND mod_merged_revid = '0' LIMIT 1 
Function: ModerationNotifyModerator::getPendingTimeUncached
Error: 1146 Table 'bitnami_mediawiki.moderation' doesn't exist (localhost:3306)

Backtrace:
#0 /opt/bitnami/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php(979): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#1 /opt/bitnami/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php(1343): Wikimedia\Rdbms\Database->query(string, string)
#2 /opt/bitnami/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php(1169): Wikimedia\Rdbms\Database->select(string, string, array, string, array, array)
#3 /opt/bitnami/apps/mediawiki/htdocs/extensions/Moderation/hooks/ModerationNotifyModerator.php(106): Wikimedia\Rdbms\Database->selectField(string, string, array, string, array)
#4 /opt/bitnami/apps/mediawiki/htdocs/extensions/Moderation/hooks/ModerationNotifyModerator.php(84): ModerationNotifyModerator::getPendingTimeUncached()
#5 /opt/bitnami/apps/mediawiki/htdocs/extensions/Moderation/hooks/ModerationNotifyModerator.php(48): ModerationNotifyModerator::getPendingTime()
#6 /opt/bitnami/apps/mediawiki/htdocs/includes/Hooks.php(177): ModerationNotifyModerator::onGetNewMessagesAlert(string, array, User, OutputPage)
#7 /opt/bitnami/apps/mediawiki/htdocs/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#8 /opt/bitnami/apps/mediawiki/htdocs/includes/skins/Skin.php(1401): Hooks::run(string, array)
#9 /opt/bitnami/apps/mediawiki/htdocs/includes/skins/SkinTemplate.php(399): Skin->getNewtalks()
#10 /opt/bitnami/apps/mediawiki/htdocs/includes/skins/SkinTemplate.php(249): SkinTemplate->prepareQuickTemplate()
#11 /opt/bitnami/apps/mediawiki/htdocs/includes/OutputPage.php(2442): SkinTemplate->outputPage()
#12 /opt/bitnami/apps/mediawiki/htdocs/includes/exception/MWExceptionRenderer.php(135): OutputPage->output()
#13 /opt/bitnami/apps/mediawiki/htdocs/includes/exception/MWExceptionRenderer.php(54): MWExceptionRenderer::reportHTML(Wikimedia\Rdbms\DBQueryError)
#14 /opt/bitnami/apps/mediawiki/htdocs/includes/exception/MWExceptionHandler.php(75): MWExceptionRenderer::output(Wikimedia\Rdbms\DBQueryError, integer)
#15 /opt/bitnami/apps/mediawiki/htdocs/includes/exception/MWExceptionHandler.php(130): MWExceptionHandler::report(Wikimedia\Rdbms\DBQueryError)
#16 /opt/bitnami/apps/mediawiki/htdocs/includes/MediaWiki.php(550): MWExceptionHandler::handleException(Wikimedia\Rdbms\DBQueryError)
#17 /opt/bitnami/apps/mediawiki/htdocs/index.php(43): MediaWiki->run()
#18 {main}

**Comment by edwardspec** [comment]
This table should have been created by update.php.

What's the output of update.php?

**Comment by savaged** [comment]
Same error when I browse to Main_Page, even after running `~/apps/mediawiki/htdocs/maintenance$ php update.php` from the ssh command line.

Here's what the command line returns:
```MediaWiki 1.30.0 Updater

pear/mail: 1.4.1 installed, ^1.4 required.
Error: your composer.lock file is not up to date. Run "composer update --no-dev" to install newer dependencies```

And I get the same after trying the recommended composer update --no-dev command (using sudo).

**Comment by edwardspec** [comment]
Please run ``maintenance/update.php --skip-external-dependencies`` to resolve this.
This is unrelated to Moderation.

**Comment by savaged** [comment]
You are a hero! Thanks, that worked perfectly.
