### ISSUE TITLE
2 rejections, 1 article and one user

### ISSUE THREAD

**Issue by SeaLancer** [edwardspec/mediawiki-moderation#44]
Hello.
I configured this addon recently in it works good but I found strange issue. If moderator wants to approve changes for one article and for one user, it can be done a many times without problems. But if moderator wants to reject changes of the article 2 and more times (for one article and user) it get an error: Fatal exception of type "Wikimedia\Rdbms\DBQueryError".  

Wiki 1.29

**Comment by edwardspec** [comment]
Could you please temporarily add `$wgShowExceptionDetails=true;` to LocalSettings.php and try rejecting the change, as you did before?
It will show more information about what caused this DBQueryError.

**Comment by SeaLancer** [comment]
Got the same error: "[a9ddb548c4f44a0b8f924041] 2019-04-05 13:20:39: Fatal exception of type "Wikimedia\Rdbms\DBQueryError""

**Comment by edwardspec** [comment]
Please also add `$wgShowSQLErrors = true;`

**Comment by SeaLancer** [comment]
плюс $wgShowDBErrorBacktrace = true; and it shows to me:

[3b0381d4232212ca935eb508] /index.php?title=Special:Moderation&modaction=reject&modid=21&token=46e9d77c2f764c4fd97438e90e8690275ca76a21%2B%5C Wikimedia\Rdbms\DBQueryError from line 1075 of C:\inetpub\wiki.tlk.net\includes\libs\rdbms\database\Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: UPDATE `moderation` SET mod_rejected = '1',mod_rejected_by_user = '4',mod_rejected_by_user_text = 'WikiAdmin',mod_preloadable=0 WHERE mod_id = '21' AND mod_merged_revid = '0' AND mod_rejected = '0'
Function: ModerationActionReject::executeRejectOne
Error: 1062 Duplicate entry '0-edit-0-My first page-[Crmadmin' for key 'moderation_load' (localhost)
Backtrace:

#0 C:\inetpub\wiki.tlk.net\includes\libs\rdbms\database\Database.php(933): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#1 C:\inetpub\wiki.tlk.net\includes\libs\rdbms\database\Database.php(1559): Wikimedia\Rdbms\Database->query(string, string)
#2 C:\inetpub\wiki.tlk.net\extensions\Moderation\action\ModerationActionReject.php(84): Wikimedia\Rdbms\Database->update(string, array, array, string)
#3 C:\inetpub\wiki.tlk.net\extensions\Moderation\action\ModerationActionReject.php(27): ModerationActionReject->executeRejectOne()
#4 C:\inetpub\wiki.tlk.net\extensions\Moderation\action\ModerationAction.php(54): ModerationActionReject->execute()
#5 C:\inetpub\wiki.tlk.net\extensions\Moderation\SpecialModeration.php(137): ModerationAction->run()
#6 C:\inetpub\wiki.tlk.net\includes\specialpage\SpecialPage.php(522): SpecialModeration->execute(NULL)
#7 C:\inetpub\wiki.tlk.net\includes\specialpage\SpecialPageFactory.php(578): SpecialPage->run(NULL)
#8 C:\inetpub\wiki.tlk.net\includes\MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#9 C:\inetpub\wiki.tlk.net\includes\MediaWiki.php(862): MediaWiki->performRequest()
#10 C:\inetpub\wiki.tlk.net\includes\MediaWiki.php(523): MediaWiki->main()
#11 C:\inetpub\wiki.tlk.net\index.php(43): MediaWiki->run()
#12 {main}

**Comment by edwardspec** [comment]
Thank you. Will investigate this.

**Comment by edwardspec** [comment]
> SET mod_rejected = '1',mod_rejected_by_user = '4',mod_rejected_by_user_text = 'WikiAdmin',**mod_preloadable=0**

Just to clarify: did you install Moderation on a wiki that didn't have it before,
or did you update Moderation from its older version (earlier than 1.2.9)?

If you re-run update.php, does this fix the problem? If not, does the output of update.php contain any errors?

**Comment by SeaLancer** [comment]
It's new Moderation install, we didn't have it before. Update.php didn't gelp пятница, 05 апреля 2019г., 18:13 +03:00 от Edward Chernenko  notifications@github.com :

**Comment by edwardspec** [comment]
Preliminary investigation: mod_preloadable=0 (in the error above) is only used when Moderation thinks that DB schema is old, and uses SQL queries for old DB schema. However, in your wiki the DB schema is not old (since you just installed it), so it fails.

What I don't yet know is why the fact "DB schema is new" wasn't recorded by update.php. It should do so on every run of update.php.

That's why I asked if update.php prints any errors. Maybe remembering "DB schema is new" is what failed during installation.

**Comment by SeaLancer** [comment]
Thank you, we will check everything again пятница, 05 апреля 2019г., 18:22 +03:00 от Edward Chernenko  notifications@github.com :

**Comment by edwardspec** [comment]
Underlying issue fixed in 1.3.31.
