### ISSUE TITLE
500 error with Moderation 1.3.0 and MediaWiki 1.32.1

### ISSUE THREAD

**Issue by billpg** [edwardspec/mediawiki-moderation#45]
Hello. I'm setting up a wiki on a cPanel commodity shared web-hosting. I have it set up and even installed a few extensions successfully. 
I tried to install Moderation by unzipping the 1.3.0 ZIP file into the extensions folder, updating the local-settings file and running the SQL update script from the browser. All seemed to work fine as a I browsed through the site and saw that Special:Version listed the new extension as expected. There was also a moderation page visible to me while logged in as WikiSysop. 
I then switched to a different browser and logged in as my "normal" user, which before installing Moderation had editing rights. (I use $wgGroupPermissions['*']['createaccount']=false; and $wgGroupPermissions['*']['edit']=false;.) 

I made a small textual edit on a page to test out the new extension. "Show Preview" worked fine but then I clicked "Save Changes", which resulted in a 500 error. 

For now, I've commented-out the new extension in my local-settings and its working again, but without Moderation. Is there anything I can do to help debug? Remember I use a cPanel host so I might not be able to dig into system log files.

(I am uncertain which is the best venue for bug reports. This is a copy from my comment on https://www.mediawiki.org/wiki/Extension_talk:Moderation#500_error_with_Moderation_1.3.0_and_MediaWiki_1.32.1 )

**Comment by edwardspec** [comment]
Please have a look at the webserver error log. It should contain the exact reason for 500.

**Comment by billpg** [comment]
Thank you so for getting back to me so quickly, but I don't know how to do that. Is this log file something I can inspect? (I'm running on a shared cPanel host.)

Is this a question I would need to ask of the host admins? If so, exactly what do I need to ask for?

**Comment by edwardspec** [comment]
By the way, Moderation 1.3.0 doesn't support MediaWiki 1.32.
The latest version of Moderation should be used instead.
( https://github.com/edwardspec/mediawiki-moderation/archive/master.zip )

**Comment by billpg** [comment]
I'll try that one instead. Thanks.

**Comment by billpg** [comment]
That did the trick. Thank you. Are there any plans to make that a formal release?

(In the meantime, you can close this ticket as resolved.)

**Comment by edwardspec** [comment]
I make releases from time to time (mainly to split the changelog),
but wikis rarely use those, since the master branch is pretty stable (it's covered by tests and all).
