### ISSUE TITLE
Bulk operations possible for Approval/Rejection?

### ISSUE THREAD

**Issue by itsTheFae** [edwardspec/mediawiki-moderation#48]
This is a feature request / question about adding Bulk actions to the Moderation page.  
Would it be possible to show a checkbox next to each entry and provide a drop-down list of actions which could be taken on each selected item?   

The current "Reject All" and "Approve All" links work well for their cases, but we are often getting spam from many different Usernames / IP addresses and over time the list can get big enough to become tedious for our moderators to go over.   A utility on the Moderation page for bulk application of the existing options would please our moderators.  

Thank you for your time.

**Comment by edwardspec** [comment]
Good idea.

**Comment by edwardspec** [comment]
Question: if you add the following line to LocalSettings.php, does it solve your problem?
```php
$wgModerationUseAjax = true;
```
In this mode, clicking on Approve, Reject, etc. won't navigate away from Special:Moderation (you can just click "Reject" on multiple lines without waiting).
So it wouldn't be much different from clicking on a checkbox.

Alternatively, one can click on Reject links with a mouse wheel (Reject action will be performed in another tab).

**Comment by itsTheFae** [comment]
Thanks for pointing this option out!  
This seems a lot less messy to me, I'll see what the rest of the team thinks about it.

**Comment by edwardspec** [comment]
Closing as resolved.
