### ISSUE TITLE
Feature request: allow anonymous uploads

### ISSUE THREAD

**Issue by jagotu** [edwardspec/mediawiki-moderation#50]
I'm runnning latest REL1_33 MediaWiki with latest master Moderation extension. I allow anonymous users to upload files by specifying `$wgGroupPermissions['*']['upload'] = true;`. However, anonymous users have no Stash, and it seems the moderation plugin can't deal with that situation. 

When I added `$wgModerationIgnoredInNamespaces[] = NS_FILE;` to LocalSettings, anonymous users can upload files again.

The bug is probably somewhere in `ModerationUploadHooks::onUploadVerifyUpload`.

**Comment by edwardspec** [comment]
Anonymous uploads are not supported.

Supporting them would require to replace Stash (which is provided by MediaWiki core, but doesn't support anonymous users) with our implementation (that would allow anonymous users to have it). It's not difficult, but it's not needed for 99.9% of wikis, so I'd rather not implement this.

**Comment by edwardspec** [comment]
Closing as implemented.

Since Moderation 1.4.6, Moderation uses the UploadStash owned by a reserved system user (instead of the uploader's UploadStash) for all uploads. Therefore **anonymous uploads are now possible**.

**Comment by jagotu** [comment]
@edwardspec Thank you very much for looking into this!

Do you have a way of accepting (small) donations? Would love to send a few bucks your way.

**Comment by edwardspec** [comment]
> Do you have a way of accepting (small) donations?

Added a Patreon link (the button near "Watch"). Hope it works (I never used it before).
