### ISSUE TITLE
Removal of deprecated SpecialPageFactory

### ISSUE THREAD

**Issue by DannyS712** [edwardspec/mediawiki-moderation#52]
Please note that the old SpecialPageFactory, deprecated in mediawiki 1.32, will likely be removed in 1.36. Its methods still have calls from this extension.

The replacement is to use MediaWikiServices::getInstance()->getSpecialPageFactory(), and use the new factory's methods. However, since this extension supports versions of MediaWiki that predate the addition of the new factory in 1.32, you will likely need to add conditional logic based on if the `MediaWiki\SpecialPage\SpecialPageFactory` class exists.

See https://phabricator.wikimedia.org/T246142 for more.

**Comment by edwardspec** [comment]
Fixed in ae31de72d238449659364ace781ba429d0d4d1f4.
