### ISSUE TITLE
how to query moderation list via api?

### ISSUE THREAD

**Issue by hyperzlib** [edwardspec/mediawiki-moderation#53]
I want to use a python script to autoreview revs, but in api document, I can't find an api to query the full list of unreviewed revs.

**Comment by edwardspec** [comment]
`api.php?action=query&list=querypage&qppage=Moderation`

This is API of MediaWiki core (it can list other query pages too - for example, `api.php?action=query&list=querypage&qppage=Ancientpages` will show contents of `Special:Ancientpages`).

**Comment by hyperzlib** [comment]
Oh thanks
