### ISSUE TITLE
Pernamently delete unapproved edits from DB

### ISSUE THREAD

**Issue by Arskrigitsioniets** [edwardspec/mediawiki-moderation#57]
I think, this extension should have a possibility to permanently delete rejected edits from DB. Some spam bots can send multiple edits and it will litter DB

**Comment by edwardspec** [comment]
You can delete them manually with the following SQL query:
`DELETE FROM moderation WHERE mod_rejected=1;`

Features that allow permanent deletion of data are too dangerous to be available from the UI.
