### ISSUE TITLE
Do not work on BlueSpice

### ISSUE THREAD

**Issue by dvlpGavin** [edwardspec/mediawiki-moderation#58]
This extension do not effect on BlueSpice.

**Comment by edwardspec** [comment]
Any support for commercial and/or heavily modified distributions of MediaWiki can only be provided on a commercial basis. 

I'm not against investigating this, but 99,9% of wikis don't use BlueSpice, and those that do are run by companies with big budgets, so investigating Bluespice-related issues is not something that can be done for free.
