### ISSUE TITLE
Sample configuration for a simple submit and return page

### ISSUE THREAD

**Issue by jehovahsays** [edwardspec/mediawiki-moderation#6]
Sorry to bother everyone about this question if it already exists<br>
I need a Sample configuration for a simple submit and return page<br>
Evertime a user creates an article and submits it they don't see <br>
A confirmation notification that their page is being reviewed<br>
And that they have to wait for me to finish reviewing the article<br>
How do I configure this? If I can't Nevermind. Thank you.

**Comment by edwardspec** [comment]
I don't understand the question.

You have some non-standard interface for editing (Special:Something) which is different from the usual editing form, and you need Moderation to work with it?

> And that they have to wait for me to finish reviewing the article
With the usual editing form, users don't need to wait for the reviewer to continue editing the article.
When you make an edit (which is queued for moderation) and then try to edit the same article again, your version of the page (which is still pending review) will be loaded into the editing form.

**Comment by jehovahsays** [comment]
I use alot of https configurations.  After a user submits they see &modqueued=1
Is that supposed to happen if it does Nevermind that. How do I return the user to a thank you for your submission page or notification

**Comment by edwardspec** [comment]
>  &modqueued=1

This is the intended behavior.
If there is "modqueued" in the URL, usual "your edit was saved" notification is replaced with "your edit was queued for moderation".

> How do I return the user to a thank you for your submission page or notification

Do you have your own PHP extension? Add
$wgOut->redirect('');
somewhere after your doEditContent() call.

**Comment by jehovahsays** [comment]
Thanks that answers my question. That's what I needed.
