### ISSUE TITLE
Add support for actor

### ISSUE THREAD

**Issue by paladox** [edwardspec/mediawiki-moderation#61]
I see stuff like rc_user_text used where as I think rc_actor needs to be used.

I don't see rc_user_text in the recentchanges table anymore.

**Comment by edwardspec** [comment]
Not a problem in this case: `rc_user_text` that we use is not a database field (which was indeed removed from MediaWiki core), but an attribute of `RecentChange` object. (used via `$rc->mAttribs['rc_user_text']`).
This field is still present in `RecentChange` object, is not deprecated, and there don't seem to be any plans to remove it.
