### ISSUE TITLE
`pagecontent` and `mwuser` tables are renamed

### ISSUE THREAD

**Issue by Ammarpad** [edwardspec/mediawiki-moderation#62]
The workaround in [ModerationTestsuite.php](https://github.com/edwardspec/mediawiki-moderation/blob/03130ecf5ccc87bcc55bb48af91323bc13f38d10/tests/phpunit/framework/ModerationTestsuite.php) for these tables (`pagecontent` and `mwuser`) in postgres schema may no longer be necessary as the tables are renamed to `text` and `user` as they are in MySQL. However `user` must still be quoted in queries since it's a reserved keyword in postgresql. `pagecontent` renaming is in 1.36, `mwuser` would probably only be in 1.37.

**Comment by edwardspec** [comment]
Fixed, thank you.
