### ISSUE TITLE
Set moderation to apply to only to certain pages instead of sitewide

### ISSUE THREAD

**Issue by aesulus** [edwardspec/mediawiki-moderation#65]
Hi there,

I'm an [admin](https://hololive.wiki/wiki/User:Aesulus) at [Hololive Fan Wiki](https://hololive.wiki/wiki/Main_Page). We've been using Extension:Moderation for a few months now and we love it! Thanks for your work on this great extension!

However, recently I've been thinking about relaxing editing restrictions, since the ratio of bad-to-good-edits we've seen in the Moderation queue has been quite small. I was wondering if it was possible to set the Moderation extension to only apply to certain pages (e.g. the Main Page, commonly used templates, etc.), kind of like a soft form of "protecting" the page. This way, users will be able to edit freely on most of the wiki, and important pages stay "protected". Moreover. any user who wants to improve a page protected by the Moderation extension will still be able to submit proposed changes to the moderation queue.

**Comment by edwardspec** [comment]
Too much work to implement. (will require a database table to keep the list of such pages, methods to add/remove/view pages in it, extending "can skip" logic to be based on title and not only on namespace, writing the associated tests... for something that 99% wikis won't use)

If there are only few pages (say, 10-20) that need protection, you can use [`ModerationIntercept` hook](https://www.mediawiki.org/wiki/Extension:Moderation/Hooks/ModerationIntercept) in your `LocalSettings.php` to achieve the desired behavior:

```php

$wgOnlyThesePagesHaveModeration = [ 'Title 1', 'Title2', 'Template:Title 3', ... ];

$wgHooks['ModerationIntercept'][] = function( WikiPage $page ) {
	global $wgOnlyThesePagesHaveModeration;

	if ( !in_array( $page->getTitle()->getFullText(), $wgOnlyThesePagesHaveModeration ) ) {
		// If false is returned, then Moderation won't intercept this edit.
		return false;
	}
};
```
