### ISSUE TITLE
Mediawiki 1.37.1 - Exception caught: Class 'Revision' not found, User::isLoggedIn was deprecated in MediaWiki 1.36

### ISSUE THREAD

**Issue by peegee355** [edwardspec/mediawiki-moderation#66]
Upgraded to mediawiki 1.37.1 and latest version of Moderation.

Now, any updates for moderation fail with "Exception caught: Class 'Revision' not found".  when I try to create a new page I get the following, ie. HELP!

Use of User::isLoggedIn was deprecated in MediaWiki 1.36. [Called from ModerationPreload::getId in /var/lib/mediawiki/extensions/Moderation/hooks/ModerationPreload.php at line 99]

AND
Backtrace:
GlobalFunctions.php line 1005 calls MWDebug::deprecated()
User.php line 2977 calls wfDeprecated()
ModerationPreload.php line 99 calls User->isLoggedIn()
ModerationNewChange.php line 74 calls ModerationPreload->getId()
QueueEditConsequence.php line 83 calls ModerationNewChange->__construct()
ConsequenceManager.php line 27 calls MediaWiki\Moderation\QueueEditConsequence->run()
ModerationEditHooks.php line 103 calls MediaWiki\Moderation\ConsequenceManager->add()
HookContainer.php line 338 calls ModerationEditHooks::onPageContentSave()
HookContainer.php line 137 calls MediaWiki\HookContainer\HookContainer->callLegacyHook()
HookRunner.php line 2714 calls MediaWiki\HookContainer\HookContainer->run()
PageUpdater.php line 807 calls MediaWiki\HookContainer\HookRunner->onPageContentSave()
WikiPage.php line 1994 calls MediaWiki\Storage\PageUpdater->saveRevision()
EditPage.php line 2351 calls WikiPage->doUserEditContent()
EditPage.php line 1687 calls EditPage->internalAttemptSave()
EditPage.php line 665 calls EditPage->attemptSave()
EditAction.php line 71 calls EditPage->edit()
SubmitAction.php line 38 calls EditAction->show()
MediaWiki.php line 543 calls SubmitAction->show()
MediaWiki.php line 320 calls MediaWiki->performAction()
MediaWiki.php line 930 calls MediaWiki->performRequest()
MediaWiki.php line 564 calls MediaWiki->main()
index.php line 53 calls MediaWiki->run()
index.php line 46 calls wfIndexMain()

AND
[e2d3b38f174f3f2013e796da] /mediawiki/index.php?title=User:Pgaccnt77&action=submit Error: Class 'Revision' not found

Backtrace:

from /var/lib/mediawiki/extensions/Moderation/lib/ModerationNewChange.php(110)
#0 /var/lib/mediawiki/extensions/Moderation/lib/consequence/QueueEditConsequence.php(84): ModerationNewChange->edit()
#1 /var/lib/mediawiki/extensions/Moderation/lib/consequence/manager/ConsequenceManager.php(27): MediaWiki\Moderation\QueueEditConsequence->run()
#2 /var/lib/mediawiki/extensions/Moderation/hooks/ModerationEditHooks.php(103): MediaWiki\Moderation\ConsequenceManager->add()
#3 /var/lib/mediawiki/includes/HookContainer/HookContainer.php(338): ModerationEditHooks::onPageContentSave()
#4 /var/lib/mediawiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#5 /var/lib/mediawiki/includes/HookContainer/HookRunner.php(2714): MediaWiki\HookContainer\HookContainer->run()
#6 /var/lib/mediawiki/includes/Storage/PageUpdater.php(807): MediaWiki\HookContainer\HookRunner->onPageContentSave()
#7 /var/lib/mediawiki/includes/page/WikiPage.php(1994): MediaWiki\Storage\PageUpdater->saveRevision()
#8 /var/lib/mediawiki/includes/EditPage.php(2351): WikiPage->doUserEditContent()
#9 /var/lib/mediawiki/includes/EditPage.php(1687): EditPage->internalAttemptSave()
#10 /var/lib/mediawiki/includes/EditPage.php(665): EditPage->attemptSave()
#11 /var/lib/mediawiki/includes/actions/EditAction.php(71): EditPage->edit()
#12 /var/lib/mediawiki/includes/actions/SubmitAction.php(38): EditAction->show()
#13 /var/lib/mediawiki/includes/MediaWiki.php(543): SubmitAction->show()
#14 /var/lib/mediawiki/includes/MediaWiki.php(320): MediaWiki->performAction()
#15 /var/lib/mediawiki/includes/MediaWiki.php(930): MediaWiki->performRequest()
#16 /var/lib/mediawiki/includes/MediaWiki.php(564): MediaWiki->main()
#17 /var/lib/mediawiki/index.php(53): MediaWiki->run()
#18 /var/lib/mediawiki/index.php(46): wfIndexMain()
#19 {main}

**Comment by peegee355** [comment]
To add, Moderation was working perfectly before I upgraded to 1.37.1

**Comment by edwardspec** [comment]
You should update Moderation to the master branch version (1.6.18).
1.5.36 release doesn't support MediaWiki 1.37.

**Comment by peegee355** [comment]
Perfect!  Many thanks - this extension is a lifesaver :-)
