### ISSUE TITLE
MediaWiki 1.37.1 - new errors

### ISSUE THREAD

**Issue by Mark-2022** [edwardspec/mediawiki-moderation#67]
Just updated MediaWiki from 1.36 to 1.37.1 and am now getting errors on my moderation extension installation.

I am running:
MediaWiki 1.37.1
PHP 8.0.13
MySql 5.7.36

The error that is being reported is below, any help to fix would be very much appreciated.

[YdnWt6xqelAX8yQunIPlEQAAwxQ] /***mywiki_name***/index.php?title=SECTION_8_-_FIREWORKS_DISPLAY_EQUIPMENT&action=submit Error: Class "Revision" not found

Backtrace:

from /***mywiki_directory_path***/extensions/Moderation/lib/ModerationNewChange.php(110)
#0 /***mywiki_directory_path***/extensions/Moderation/lib/consequence/QueueEditConsequence.php(84): ModerationNewChange->edit()
#1 /***mywiki_directory_path***/extensions/Moderation/lib/consequence/manager/ConsequenceManager.php(27): MediaWiki\Moderation\QueueEditConsequence->run()
#2 /***mywiki_directory_path***/extensions/Moderation/hooks/ModerationEditHooks.php(103): MediaWiki\Moderation\ConsequenceManager->add()
#3 /***mywiki_directory_path***/includes/HookContainer/HookContainer.php(338): ModerationEditHooks::onPageContentSave()
#4 /***mywiki_directory_path***/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#5 /***mywiki_directory_path***/includes/HookContainer/HookRunner.php(2714): MediaWiki\HookContainer\HookContainer->run()
#6 /***mywiki_directory_path***/includes/Storage/PageUpdater.php(807): MediaWiki\HookContainer\HookRunner->onPageContentSave()
#7 /***mywiki_directory_path***/includes/page/WikiPage.php(1994): MediaWiki\Storage\PageUpdater->saveRevision()
#8 /***mywiki_directory_path***/includes/EditPage.php(2351): WikiPage->doUserEditContent()
#9 /***mywiki_directory_path***/includes/EditPage.php(1687): EditPage->internalAttemptSave()
#10 /***mywiki_directory_path***/includes/EditPage.php(665): EditPage->attemptSave()
#11 /***mywiki_directory_path***/includes/actions/EditAction.php(71): EditPage->edit()
#12 /***mywiki_directory_path***/includes/actions/SubmitAction.php(38): EditAction->show()
#13 /***mywiki_directory_path***/includes/MediaWiki.php(543): SubmitAction->show()
#14 /***mywiki_directory_path***/includes/MediaWiki.php(320): MediaWiki->performAction()
#15 /***mywiki_directory_path***/includes/MediaWiki.php(930): MediaWiki->performRequest()
#16 /***mywiki_directory_path***t/includes/MediaWiki.php(564): MediaWiki->main()
#17 /***mywiki_directory_path***/index.php(53): MediaWiki->run()
#18 /***mywiki_directory_path***/index.php(46): wfIndexMain()
#19 {main}

**Comment by edwardspec** [comment]
See #66.

**Comment by Mark-2022** [comment]
Thank you, my apologies for not seeing #66 before posting.
