### ISSUE TITLE
Can it work with echo extensions？

### ISSUE THREAD

**Issue by MisaWki** [edwardspec/mediawiki-moderation#68]
Sorry, my English is not good, so this issue is translated by translation software. I want to ask if this extension can interact with echo.

**Comment by edwardspec** [comment]
1) It can be installed alongside Extension:Echo.
2) Moderation doesn't send Echo notifications, and adding them is not planned.
See [https://www.mediawiki.org/wiki/Extension_talk:Moderation/Archive_1#Works_with_Echo?](https://www.mediawiki.org/wiki/Extension_talk:Moderation/Archive_1#Works_with_Echo?)
