### ISSUE TITLE
console error when using moderation plugin

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#7]
I get this console error "VM15430:39 Uncaught TypeError: String.split is not a function" using the moderation plugin, which otherwise is working fine ...

![](https://www.dropbox.com/s/q3dcyf1ker920j1/Screenshot%202017-05-01%2011.17.35.png?dl=1)

**Comment by edwardspec** [comment]
1. Which browser do you use?

2. Does the error disappear if you replace
`for ( pair of String.split( sendBody, '&' ) ) {`
with 
`for ( pair of (new String( sendBody )).split( '&' ) ) {`
in modules/ext.moderation.ajaxhook.js ?

**Comment by tansaku** [comment]
It was happening in Chrome Version 57.0.2987.133 (64-bit) on OSX, but it's stopped now - I did just turn off debugging in parsoid ...

**Comment by edwardspec** [comment]
Problem reproduced (this happened when saving an edit in MobileFrontend editor in Google Chrome).
Fixed in 1.0.17.
