### ISSUE TITLE
Call to undefined method User::isLoggedIn()

### ISSUE THREAD

**Issue by TechDepositoryWiki** [edwardspec/mediawiki-moderation#71]
Hello, today I went and updated my wiki to version 1.38.1, and when I go to edit a page this error appears... If I remove this extension issue goes away...

[28fea7c90c0ab64f9ead8811] /wiki/Serial_ATA?action=edit&veswitched=1&oldid=0 Error: Call to undefined method User::isLoggedIn()

Backtrace:

from /home/techjgrp/public_html/extensions/Moderation/hooks/ModerationPreload.php(99)
#0 /home/techjgrp/public_html/extensions/Moderation/hooks/ModerationPreload.php(167): ModerationPreload->getId()
#1 /home/techjgrp/public_html/extensions/Moderation/hooks/ModerationPreload.php(190): ModerationPreload->findPendingEdit()
#2 /home/techjgrp/public_html/extensions/Moderation/hooks/ModerationPreload.php(229): ModerationPreload->showPendingEdit()
#3 /home/techjgrp/public_html/includes/HookContainer/HookContainer.php(338): ModerationPreload::onEditFormPreloadText()
#4 /home/techjgrp/public_html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#5 /home/techjgrp/public_html/includes/HookContainer/HookRunner.php(1482): MediaWiki\HookContainer\HookContainer->run()
#6 /home/techjgrp/public_html/includes/EditPage.php(685): MediaWiki\HookContainer\HookRunner->onEditFormPreloadText()
#7 /home/techjgrp/public_html/includes/actions/EditAction.php(71): EditPage->edit()
#8 /home/techjgrp/public_html/includes/MediaWiki.php(544): EditAction->show()
#9 /home/techjgrp/public_html/includes/MediaWiki.php(321): MediaWiki->performAction()
#10 /home/techjgrp/public_html/includes/MediaWiki.php(910): MediaWiki->performRequest()
#11 /home/techjgrp/public_html/includes/MediaWiki.php(564): MediaWiki->main()
#12 /home/techjgrp/public_html/index.php(53): MediaWiki->run()
#13 /home/techjgrp/public_html/index.php(46): wfIndexMain()
#14 {main}

**Comment by edwardspec** [comment]
You have outdated version of Moderation, current version (1.6.21) doesn't use `isLoggedIn()`.
