### ISSUE TITLE
The "Success: your edit has been sent to moderation." message from extension:Moderation shows up as an error in VisualEditor master branch

### ISSUE THREAD

**Issue by orchardstreet** [edwardspec/mediawiki-moderation#73]
The "Success: your edit has been sent to moderation." message from extension:Moderation shows up as an error in VisualEditor master branch

Used to show the text without being in an error box, in previous visualeditor versions

Now it shows the message in an errorbox and asks the user to try to submit the text again.  But the edit does go through to moderation.

The full error shows as :
>Something went wrong

>Success: your edit has been sent to moderation.

>You can continue editing <a href='$1'>your version of this page</a>.

>Dismiss - Try Again

**Comment by edwardspec** [comment]
Moderation only supports VisualEditor for already released versions of MediaWiki. Which means only MediaWiki 1.38 today.

It's not feasible to support the master branch of VisualEditor, which already requires adjustments (sometimes major ones) after almost every release of MediaWiki. Supporting master branch of VisualEditor and other third-party extensions might mean making these fixes 100 times a year for issues that 99,99% of users will never see.

Support for 1.39 can only be investigated after MediaWiki core developers cut off their REL1_39 branch, and VisualEditor developers cut off their REL1_39 branch. Even after that, it's not urgent until MediaWiki 1.39 is officially released.

**Comment by edwardspec** [comment]
Fixed in Moderation 1.7.0.
