### ISSUE TITLE
BagOStuff::decr() method is deprecated/removed

### ISSUE THREAD

**Issue by Krinkle** [edwardspec/mediawiki-moderation#76]
> `BagOStuff::decr()`, deprecated since 1.28, has been removed in 1.40.

For your attention, as of <https://gerrit.wikimedia.org/r/c/mediawiki/core/+/896438/>.

It looks like it is ununsed, only there to satisfy an interface. If you do need something like it, there is `incrWithInit()` which can be called with `-1`.

**Comment by edwardspec** [comment]
Thanks. It being removed won't break anything, so no action is required.

> It looks like it is unused, only there to satisfy an interface.

Testsuite still needs to run in 1.35-1.39, so can't remove `ModerationTestsuiteBagOStuff::decr()` for now.
