### ISSUE TITLE
[Feature Request] Wiki family support

### ISSUE THREAD

**Issue by DerfJagged** [edwardspec/mediawiki-moderation#77]
I run a 8 different wikis under one wiki family (farm). Moderation is installed which is great for vandalism control, but it requires moderators to manually check each wiki separately in order to see the "edits pending" notification. It would be nice to have an the notifications show regardless of what wiki the moderator is looking at, similar to [cross-wiki notifications on Wikimedia wikis](https://m.mediawiki.org/wiki/Help:Notifications/Cross-wiki).

**Comment by edwardspec** [comment]
It would indeed be useful, even on my own wikis. It's a low priority
task for now, but I plan to look into this at some point.

Implementation would need to be considered very carefully: to not
impact performance, to account for possibility that different wikis
may have different moderators, to make automated tests of this feature
possible without setting up more than 1 wiki, to avoid mistakes that
would require changing database schema later, etc.


2023-05-13 8:17 GMT+03:00, Derf ***@***.***>:

**Comment by edwardspec** [comment]
Can be reopened later if someone else wants to implement this.
