### ISSUE TITLE
Internal error when trying to open Special:Moderation (avid.wiki)

### ISSUE THREAD

**Issue by Hb1290** [edwardspec/mediawiki-moderation#81]
As the title states when we try to use Special:Moderation, we get an internal error message. Our technician found the error:
`Error: Call to undefined method MediaWiki\Output\OutputPage::preventClickJacking() `

He informed me this was an issue with the extension itself rather than our setup.

**Comment by edwardspec** [comment]
This is happening, because you are using master branch of MediaWiki core, which shouldn't be used in production.
