### ISSUE TITLE
[Request] Change successful submission message from fatal()

### ISSUE THREAD

**Issue by DerfJagged** [edwardspec/mediawiki-moderation#83]
Many users on my site get confused when they submit a change in the Visual Editor and the "your edit was sent to moderation" message says "Something went wrong" at the top and has a red background. It appears to be an error to them, and they don't think their edit went through.

Poking in the source, I see it throws a fatal() for it. Could this be changed to some other sort of message? I played around with removing it, but it appears to break functionality.

**Comment by edwardspec** [comment]
Are you using outdated version of Moderation? It shows "your edit was sent to moderation" if you aren't.

**Comment by edwardspec** [comment]
What version of Moderation and MediaWiki are you using?
It's already a thing, so you may be using an outdated version.

**Comment by DerfJagged** [comment]
I'm using:

MediaWiki 1.39.6
Moderation 1.6.22 (updated last night to see if it would fix it)
VisualEditor: Version file says 2023-12-26T07:23:10, 1e78910 - but Special:Version says 0.1.2 (65d89c9, January 31st 2023).

**Comment by edwardspec** [comment]
1.6.22 is ancient and doesn't support MediaWiki 1.39. Please use the latest version.

**Comment by DerfJagged** [comment]
If the main branch _is_ 1.7.7, it's not clear. Either a new release should be put on the [releases page](https://github.com/edwardspec/mediawiki-moderation/releases) or the releases should all be removed including version tags and branches since they all appear to stop at 1.6.22. Even the [MediaWiki.org page](https://www.mediawiki.org/wiki/Extension:Moderation) says 1.6.19 is the latest.

**Comment by edwardspec** [comment]
You are not supposed to be using these "releases" at all. The installation instructions on mediawiki.org clearly state to use the branch. Releases are for older versions of MediaWiki (I will update their title to reflect that).

MediaWiki 1.41 is about to be releases soon, a new release can be made after that.
