### ISSUE TITLE
issue after upgrade to 1.41

### ISSUE THREAD

**Issue by cariaso** [edwardspec/mediawiki-moderation#84]
[error] 1823#1823: *1080 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Use of Modules must target desktop and mobile. Module name:ext.moderation.mf.notify was deprecated in MediaWiki 1.41. [Called from MediaWiki\ResourceLoader\StartUpModule::getScript in /srv/sites/mw/live/includes/ResourceLoader/StartUpModule.php at line 436] in /srv/sites/mw/live/includes/debug/MWDebug.php on line 386PHP message: PHP Deprecated:  Use of Modules must target desktop and mobile. Module name:ext.moderation.mf.preload33 was deprecated in MediaWiki 1.41. [Called from MediaWiki\ResourceLoader\StartUpModule::getScript in /srv/sites/mw/live/includes/ResourceLoader/StartUpModule.php at line 436] in /srv/sites/mw/live/includes/debug/MWDebug.php on line 386PHP message: PHP Deprecated:  Use of Modules must target desktop and mobile. Module name:ext.moderation.notify.desktop was deprecated in MediaWiki 1.41. [Called from MediaWiki\ResourceLoader\StartUpModule::getScript in /srv/sites/mw/live/includes/ResourceLoader/StartUpModule.php at line 436] in /srv/sites/mw/live/includes/debug/MWDebug.php on line 386PHP message: PHP Deprecated:  Use of Modules must target desktop and mobile. Module name:ext.moderation.ve was deprecated in MediaWiki 1.41. [Called from MediaWiki\ResourceLoader\StartUpModule::getScript in /srv/sites/mw/live/includes/ResourceLoader/StartUpModule.php at line 436] in /srv/sites/mw/live/includes/debug/MWDebug.php on line 386" while reading response header from upstream, client: 173.66.189.185,

**Comment by edwardspec** [comment]
The warning is harmless until 1.42.

There is no quick fix (intended way to remove this warning, unfortunately, comes with the necessity to abandon backward compatibility with all previous versions of MediaWiki, including 1.39 LTS), but I will look for a workaround.
