### ISSUE TITLE
How do I provide translations for API help

### ISSUE THREAD

**Issue by xiaofeiTM233** [edwardspec/mediawiki-moderation#87]
the i18n json in /api/i18n directory was not handed over to translatewiki.net for translation, so how should we provide the translation?

**Comment by edwardspec** [comment]
API messages don't need translation. The only people who read them are developers, it would be nothing but a waste of time to translate them.

**Comment by xiaofeiTM233** [comment]
> The only people who read them are developers

I see. Thank you for your reply
It is true that developers are usually capable of understanding English  lol
