### ISSUE TITLE
Edit notice for users subject to moderation

### ISSUE THREAD

**Issue by ProbablePrime** [edwardspec/mediawiki-moderation#88]
I frequently have users who are confused by our use of this moderation extension. They don't realize it is in place.

I thought A https://www.mediawiki.org/wiki/Manual:Interface/Edit_notice, might help.

For example the Translate extension adds a notice for various reasons when the page is translated and edited, with a hook: https://github.com/wikimedia/mediawiki-extensions-Translate/blob/master/src/PageTranslation/Hooks.php#L304

For now I'll use the "MediaWiki:Editnotice-N" page to add a notice so that users are not confused, but adding this into the code base here would allow for it to be tied into the settings, groups etc system that this extension adds.

I might contribute this myself, but am making the issue before I do so for discussion.

EDIT: Also found this: https://phabricator.wikimedia.org/T312587 where Mediawiki added edit notices for mobile editors.

**Comment by edwardspec** [comment]
User can already see the message [[MediaWiki:Moderation-edit-queued]], which explains everything. This is shown after every edit (both on desktop and mobile).

**Comment by ProbablePrime** [comment]
Oh I apologize, I wasn't aware of this page!

I will close this issue, thank you!!
