### ISSUE TITLE
Moderation doesn't happen

### ISSUE THREAD

**Issue by mattheimer** [edwardspec/mediawiki-moderation#89]
Users not belonging to sysop, automoderated, moderator, etc can edit without issue and the edits appear publicly and the moderation log remains empty.

https://wiki.osdev.org/Special:Version

I'm running MediaWiki 1.39.7
I tried both cloning this repo's master branch on 6/22/2024 and installing from the 1.7.9 release tarball.

You can see the extension loaded and only moderator members can access the Special:Moderation page.

But users that belong to no groups except the implicit Autoconfirmed group can edit pages without restriction or moderation.

Is it possible that this extension doesn't work with PluggableAuth? I'm using https://www.mediawiki.org/wiki/Extension:PluggableAuth (which is the foundation part) and https://www.mediawiki.org/wiki/Extension:PHPBB_Auth which sets my Mediawiki so that you log into the wiki using a PHPBB account.

Any other possible causing of moderation being skipped? $wgModerationEnable is not defined.

**Comment by edwardspec** [comment]
Remove "rollback" right from "Users" group. Due to how quick rollback works, it also allows to bypass moderation.

**Comment by mattheimer** [comment]
Thank you so much, that was it!
